[features]
seeds = false

# [programs.localnet]
# perpetuals = "FastuHRd9PRiuKGy2dHgH4zcSRjARKnPcHiQZnxpR5fD"
[programs.devnet]
perpetuals = "FastuHRd9PRiuKGy2dHgH4zcSRjARKnPcHiQZnxpR5fD"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/Beta-Hcik.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 programs/perpetuals/tests/anchor/*.ts"
